networks:
  traefik:
    external: false

services:

  traefik:
    image: traefik:v3.3.2
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik_data:/letsencrypt
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=flake@uni-koblenz.de"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
  
  pdc:
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pdc.rule=Host(`${PDC_DOMAIN_NAME}`)"
      - "traefik.http.routers.pdc.entrypoints=websecure"
      - "traefik.http.routers.pdc.tls=true"
      - "traefik.http.routers.pdc.tls.certresolver=le"
      - "traefik.http.services.pdc.loadbalancer.server.port=${PDC_PORT}"

  # TODO Needs to be isolated from outside world. Connection from outside only via PDC
  nginx:
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`carisma-reports.ptx.uni-koblenz.de`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=le"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
