services:
  
  carisma:
    build:
      context: ./carisma-tool/docker/remote
      args:
        # You can overwrite the CARiSMA release to use
        # CARISMA_RELEASE_URL: https://github.com/CARiSMA-Tool/carisma-tool/releases/latest/download/carisma-product-linux.gtk.x86_64.tar.gzcarisma-product-linux.gtk.x86_64.tar.gz
    ports:
      - "2222:22"
    volumes:
      - ./volumes/authorized_keys:/root/.ssh/authorized_keys:ro
      - ./volumes/workspace:/root/workspace
      
  # TODO Needs to be isolated from outside world. Connection from outside only via PDC
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./volumes/workspace/carisma-reports/public:/usr/share/nginx/html:ro
    environment:
      # - NGINX_HOST=carisma.ptx.uni-koblenz.de
      - NGINX_PORT=80
