services:
  
  carisma:
    build: ./carisma-tool/docker/remote
    ports:
      - "2222:22"
    volumes:
      - ./volumes/authorized_keys:/root/.ssh/authorized_keys:ro
      - ./volumes/carisma-reports:/root/carisma-reports
      - ./volumes/carisma-examples:/root/carisma-examples
      
  # TODO Needs to be isolated from outside world. Connection from outside only via PDC
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./volumes/carisma-reports/:/usr/share/nginx/html:ro
    environment:
      - NGINX_HOST=carisma.ptx.uni-koblenz.de
      - NGINX_PORT=80
