@startjson
{
    "name" : "AI Scenario Analysis",
    "success" : false,
    "analyses" : [{
	"name": "PersonalDataAnalysis",
	"success": true,
	"info": "Data contains no  personal information"
    }, {
	"name": "AiAlgorithmsAnalysis",
	"success": false,
	"info": "Algorithm X possible Data Poisoning Attack"
    }, {
	"name": "...",
	"success": "...",
	"info": "..."
    }],
    "report": {
	"html": "<html><head>...</head><body>...</body></html>",
	"xml": "<xml>...</xml>",
	"rdf" : "{\"@context\": {...}}"
    }
}
@endjson
