@startuml

actor "Use Case Lead\n(AI Expert)" as a
participant "CARiSMA\nModeller" as cm
participant "CARiSMA\nAnalyzer" as ca
participant "PDC @BB04\n(Provider)" as pdc1
participant "PDC @BB07\n(Consumer)" as pdc2
participant "Distributed\nData Visualizer" as v
actor "User\n(Data subject)" as u


a -> cm : Create Model & Specification
a -> cm : Annotate Model with AI specifics
a -> ca : Create Analysis Definition File
cm -> ca : Model
a -> ca : Start Analysis
ca -> ca : Analysis of the Model
a -> ca : View Results & Report
ca -> ca : Render Results & Report
a -> ca : Share Results & Report
note right
	Check, whether involvement
	of Catalog and Contract
	is necessary
end note
ca -> pdc1 : Results & Report
pdc1 -> pdc2 : Results & Report
pdc2 -> v : Results & Report
v -> v : Render Results & Report
v <- u : View Results & Report
@enduml
