@startuml
left to right direction

actor u as "User\n(Data Subject)"
actor a as "Use Case Lead\n(AI Expert)"

package "Trustworthy AI: CARiSMA" {
	usecase UcCreate as "Create AI Scenario Model"
	usecase UcAnalyze as "Analyze AI Scenario Model"
	usecase UcView as "Create & View AI Analysis Report"
	usecase UcImprove as "Improve AI Scenario Model"
	usecase UcShare as "Share AI Analysis Report"
}
package "Distributed Data Visualization" {
	usecase UcDdView as "View AI Analysis Report"
}

a --> UcCreate
a --> UcAnalyze
a --> UcView
a --> UcImprove
a --> UcShare
u --> UcDdView

@enduml
